global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'extraction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['extraction-service:8080']

  - job_name: 'classification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['classification-service:8081']

  - job_name: 'gmail-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gmail-service:8090']

  - job_name: 'job-search-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['job-search-processor:8083']
